### PR TITLE
Switch to current version of test suite

### PR DESCRIPTION
**Pull request by joewiz**
As noted in https://github.com/eXist-db/exist-xqts-runner/issues/1:

> the version downloaded by default, QT3_1_0, is from June 2013, when 3.1 was just a draft

### CODE REVIEW

**Comment by joewiz** [comment]
My immediate motivation for this PR was that I tried running the tests for `map:remove()`—using the `--test-set map-remove` flag—and I got errors saying that eXist no longer supports the `:=` notation for creating map entries. I was surprised that the tests would be using that old notation... That reminded me of the issue here.

**Comment by adamretter** [comment]
@joewiz I really like this, but my concern is that by taking the HEAD of `master` we are trying to hit a moving target.

**Comment by joewiz** [comment]
@adamretter Ideally, the maintainers would apply a tag and pull releases. Perhaps we should fork it, so we control HEAD?

**Comment by joewiz** [comment]
@adamretter Perhaps we should raise this question of the "moving target" in xquery-talk? I imagine that other projects have had to tackle this issue.

**Comment by adamretter** [comment]
@joewiz I updated this, so that multiple versions of the xqts are supported. To use the version from GitHub, you can now pass the argument `--xqts-version HEAD` or `-x HEAD`.

**Pull request merged**
