### PR TITLE
Fix dependency with removed internal class.

### PR DESCRIPTION
**Pull request by dizzzz**
as reported by @joewiz in https://github.com/eXist-db/exist/pull/3530#issuecomment-711115414

### CODE REVIEW

**Review by joewiz — APPROVED** [review]
Hmm, the PR fails CI checks:

```txt
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.exist-db:exist-core:5.3.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/travis/.ivy2/local/org.exist-db/exist-core/5.3.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/exist-db/exist-core/5.3.0-SNAPSHOT/exist-core-5.3.0-SNAPSHOT.pom
[error]   not found: /home/travis/.m2/repository/org/exist-db/exist-core/5.3.0-SNAPSHOT/exist-core-5.3.0-SNAPSHOT.pom
[error]   not found: https://repo.evolvedbinary.com/repository/exist-db/org/exist-db/exist-core/5.3.0-SNAPSHOT/exist-core-5.3.0-SNAPSHOT.pom
[error]   not found: https://repo.evolvedbinary.com/repository/exist-db-snapshots/org/exist-db/exist-core/5.3.0-SNAPSHOT/exist-core-5.3.0-SNAPSHOT.pom
[error]   not found: https://raw.github.com/eXist-db/mvn-repo/master/org/exist-db/exist-core/5.3.0-SNAPSHOT/exist-core-5.3.0-SNAPSHOT.pom
```

... but building the PR locally works, having pre-installed eXist 5.3.0-SNAPSHOT:

```txt
% sbt compile
[info] Loading settings for project exist-xqts-runner-build from assembly.sbt,license.sbt,header.sbt,plugins.sbt ...
[info] Loading project definition from /Users/joe/workspace/exist-xqts-runner/project
[info] Loading settings for project exist-xqts-runner from build.sbt ...
[info] Set current project to exist-xqts-runner (in build file:/Users/joe/workspace/exist-xqts-runner/)
[info] Executing in batch mode. For better performance use sbt's shell
[warn] Credentials file /Users/joe/.ivy2/.credentials does not exist
[warn] Credentials file /Users/joe/.ivy2/.credentials does not exist
[warn] Credentials file /Users/joe/.ivy2/.credentials does not exist
[success] Total time: 1 s, completed Oct 19, 2020, 11:23:00 AM
```

So I think we'd be in good shape to merge this, right?

**Comment by adamretter** [comment]
It's a good start but it's on the wrong branch. I have cherry-picked it to the 5.3.0-SNAPSHOT branch. I am also making the other needed fixes for 5.3.0 in there

**Comment by joewiz** [comment]
@adamretter Oh! Ok. That might explain #11.

**Comment by adamretter** [comment]
@dizzzz Thanks I have merged this to the 5.3.0-SNAPSHOT branch.

Closed by 1f3e1aa35a5cd2db184e4663379963ef6a3f754f

**Pull request closed without merging**
